[project]
name = "reg_model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.3.1",
    "click>=8.3.3",
    "platformdirs>=4.9.6",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.0",
    "ruff>=0.15.12",
    "structlog>=25.5.0",
    "tomli>=2.4.1",
    "tomli-w>=1.2.0",
    "typer>=0.25.1",
    "typing-extensions>=4.15.0",
]
lint = [
    "ruff",
]

[project.scripts]
reg_model = "reg_model.main:main"

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
